# SARMS Backend
spring.application.name=sarms-backend
server.port=8080

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://Aryan:123A456@sarms.bhpgxx2.mongodb.net/sarms_db?retryWrites=true&w=majority
spring.data.mongodb.database=sarms_db

# JWT Configuration
jwt.secret=SarmsJwtSecretKey2026VeryLongStringForHMACSHA256AlgorithmSecurity
jwt.expiration=86400000

# CORS - allow React frontend (Vite default port)
cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:3000

# Logging
logging.level.com.sarms=DEBUG
logging.level.org.springframework.data.mongodb=INFO
